
from __future__ import annotations

from strace_macos.syscalls import numbers

from strace_macos.syscalls.definitions import (
    BufferParam,
    ConstParam,
    CustomParam,
    DirFdParam,
    FileDescriptorParam,
    FlagsParam,
    FlockOpParam,
    IntParam,
    OctalParam,
    ParamDirection,
    PointerParam,
    StringParam,
    SyscallDef,
    UidGidParam,
    UnsignedParam,
    VariantParam,
)

from strace_macos.syscalls.struct_params import (
    AttrListParam,
    FssearchblockParam,
    IntPtrParam,
    IovecParam,
    StatfsParam,
    StatParam,
    TermiosParam,
    WinsizeParam,
)

MACH_TRAPS: list[SyscallDef] = [
    SyscallDef(numbers.TRAP_kernelrpc_mach_vm_allocate_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_vm_purgable_control_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_vm_deallocate_trap, "", params=()),
    SyscallDef(numbers.TRAP_task_dyld_process_info_notify_get_trap , "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_vm_protect_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_vm_map_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_allocate_trap , "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_deallocate_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_mod_refs_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_move_member_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_insert_right_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_insert_member_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_extract_member_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_construct_trap, "", params=()),
    SyscallDef(numbers.TRAP_kernelrpc_mach_port_destruct_trap, "", params=()),
    SyscallDef(numbers.TRAP_mach_reply_port, "", params=()),
    SyscallDef(numbers.TRAP_thread_self_trap, "", params=()),
    SyscallDef(numbers.TRAP_task_self_trap, "", params=()),
    SyscallDef(numbers.TRAP_host_self_trap, "", params=()),
    SyscallDef(numbers.TRAP_mach_msg_trap, "", params=()),
    SyscallDef(numbers.TRAP_mach_msg_overwrite_trap, "", params=()),
    SyscallDef(numbers.TRAP_semaphore_signal_trap, "", params=()),
    SyscallDef(numbers.TRAP_semaphore_signal_all_trap, "", params=()),
    SyscallDef(numbers.TRAP_semaphore_signal_thread_trap, "", params=()),
    SyscallDef(numbers.TRAP_semaphore_wait_trap, "", params=()),
    SyscallDef(numbers.TRAP_semaphore_wait_signal_trap, "", params=()),
    SyscallDef(numbers.TRAP_semaphore_timedwait_trap, "", params=()),
    SyscallDef(numbers.TRAP_semaphore_timedwait_signal_trap, "", params=()),
    SyscallDef(numbers.TRAP__kernelrpc_mach_port_get_attributes_trap , "", params=()),
    SyscallDef(numbers.TRAP__kernelrpc_mach_port_guard_trap, "", params=()),
    SyscallDef(numbers.TRAP__kernelrpc_mach_port_unguard_trap, "", params=()),
    SyscallDef(numbers.TRAP_mach_generate_activity_id, "", params=()),
    SyscallDef(numbers.TRAP_task_name_for_pid, "", params=()),
    SyscallDef(numbers.TRAP_task_for_pid, "", params=()),
    SyscallDef(numbers.TRAP_pid_for_task, "", params=()),
    SyscallDef(numbers.TRAP_mach_msg2_trap, "", params=()),
    SyscallDef(numbers.TRAP_macx_swapon, "", params=()),
    SyscallDef(numbers.TRAP_macx_swapoff, "", params=()),
    SyscallDef(numbers.TRAP_thread_get_special_reply_port, "", params=()),
    SyscallDef(numbers.TRAP_macx_triggers, "", params=()),
    SyscallDef(numbers.TRAP_macx_backing_store_suspend, "", params=()),
    SyscallDef(numbers.TRAP_macx_backing_store_recovery, "", params=()),
    SyscallDef(numbers.TRAP_pfz_exit, "", params=()),
    SyscallDef(numbers.TRAP_swtch_pri, "", params=()),
    SyscallDef(numbers.TRAP_swtch, "", params=()),
    SyscallDef(numbers.TRAP_thread_switch, "", params=()),
    SyscallDef(numbers.TRAP_clock_sleep_trap, "", params=()),
    SyscallDef(numbers.TRAP_host_create_mach_voucher_trap , "", params=()),
    SyscallDef(numbers.TRAP_mach_voucher_extract_attr_recipe_trap, "", params=()),
    SyscallDef(numbers.TRAP__kernelrpc_mach_port_type_trap, "", params=()),
    SyscallDef(numbers.TRAP__kernelrpc_mach_port_request_notification_trap, "", params=()),
    SyscallDef(numbers.TRAP__exclaves_ctl_trap, "", params=()),
    SyscallDef(numbers.TRAP_mach_timebase_info_trap , "", params=()),
    SyscallDef(numbers.TRAP_mach_wait_until_trap, "", params=()),
    SyscallDef(numbers.TRAP_mk_timer_create_trap, "", params=()),
    SyscallDef(numbers.TRAP_mk_timer_destroy_trap, "", params=()),
    SyscallDef(numbers.TRAP_mk_timer_arm_trap, "", params=()),
    SyscallDef(numbers.TRAP_mk_timer_cancel_trap , "", params=()),
    SyscallDef(numbers.TRAP_mk_timer_arm_leeway_trap, "", params=()),
    SyscallDef(numbers.TRAP_debug_control_port_for_pid, "", params=()),
]
